---
# https://taskfile.dev

version: "3"

vars:
  GO_OS: "windows" # Default OS
  GO_ARCH: "amd64" # Default architecture
  APP_NAME: "enex2paperless" # Application name

tasks:
  release:
    desc: Use goreleaser to create a release
    dotenv:
      - github_token.env
    cmds:
      - goreleaser release --clean

  run:
    desc: run main
    cmds:
      - go run cmd/main/main.go

  build:
    internal: true
    vars:
      GO_OS: "{{ .GO_OS }}"
      GO_ARCH: "{{ .GO_ARCH }}"
    cmds:
      - GOOS={{ .GO_OS }} GOARCH={{ .GO_ARCH }} go build -o build/{{ .APP_NAME }}_{{ .GO_OS }}_{{ .GO_ARCH }} cmd/main/main.go

  build_windows:
    desc: Build for Windows (amd64)
    cmds:
      - task: build
        vars:
          GO_OS: "windows"

  build_linux:
    desc: Build for Linux (amd64)
    cmds:
      - task: build
        vars:
          GO_OS: "linux"

  build_darwin:
    desc: Build for macOS (amd64)
    cmds:
      - task: build
        vars:
          GO_OS: "darwin"

  build_all:
    desc: Build for all OS
    cmds:
      - task: build_windows
      - task: build_linux
      - task: build_darwin

  test:
    desc: Run all tests with verbose output
    cmds:
      - go test -v ./...
