---
# https://taskfile.dev

version: "3"

vars:
  GO_OS: "windows" # Default OS
  GO_ARCH: "amd64" # Default architecture
  APP_NAME: "enex2paperless" # Application name

tasks:
  paperless:up:
    desc: Start Test Instance
    cmds:
      - sudo docker compose up -d

  paperless:down:
    desc: Kill Test Instance
    cmds:
      - sudo docker compose down -v

  release:
    desc: Use goreleaser to create a release
    preconditions:
      - sh: gh auth status
        msg: "You need to login to GitHub first. Run 'gh auth login'"
    dotenv:
      - github_token.env
    cmds:
      - goreleaser release --clean {{.CLI_ARGS}}

  run:
    desc: run main
    cmds:
      - go run cmd/main/main.go {{.CLI_ARGS}}

  build:
    internal: true
    vars:
      GO_OS: "{{ .GO_OS }}"
      GO_ARCH: "{{ .GO_ARCH }}"
    cmds:
      - GOOS={{ .GO_OS }} GOARCH={{ .GO_ARCH }} go build -o build/{{ .APP_NAME }}_{{ .GO_OS }}_{{ .GO_ARCH }} cmd/main/main.go

  build:windows:
    desc: Build for Windows (amd64)
    cmds:
      - task: build
        vars:
          GO_OS: "windows"

  build:linux:
    desc: Build for Linux (amd64)
    cmds:
      - task: build
        vars:
          GO_OS: "linux"

  build:darwin:
    desc: Build for macOS (amd64)
    cmds:
      - task: build
        vars:
          GO_OS: "darwin"

  build:all:
    desc: Build for all OS
    cmds:
      - task: build:windows
      - task: build:linux
      - task: build:darwin

  test:
    desc: Run all tests with verbose output
    dir: .
    cmds:
      - gotest -v ./...

  test:integration:
    desc: Run integration tests (requires Paperless instance)
    dir: .
    cmds:
      - gotest -count=1 -v -tags=integration ./test/integration/...
